### PR TITLE
Convert Project to .NET Standard and disposal reordering

### LINKED ISSUE #11: Does not force flush on disposal
I have a console app that executes quite quickly and the number of messages is inconsistently relayed to Slack. (i.e out of 6 log messages, sometimes I might see 1 or 2 or 3 but never the full 6.

I understand the limitations of posting to a webhook but I thought that as long as I am disposing correctly that the sink would be fully flushed? Maybe a synchronous option if people really want this enforced?

Thoughts?

### PR DESCRIPTION
**Pull request by TrapperHell**
- Convert deprecated xproj project format to csproj
- Add .NET Standard 2.0 as a project target
- Reorder HttpClient disposal to allow sufficient time for logger disposal to use the HttpClient
- Remove the static marking for HttpClient to allow re-initialization and re-use of said client
- Possible issue fix #11
- Add generic Serilog Sink icon
- Remove empty license file
- Remove GitCheese reference
- Minor reformatting
- Move model and option files to Models directory
- Adjust typo in Readme
- Reorder exception so that it shows up before Stack Trace

### CODE REVIEW

**Comment by ps30** [comment]
Great and thanks for keeping this project fresh.  If this PR does not get in soon, have you thought about pushing a NuGet package from your repo?  Any plans for .Net 5 support?

**Comment by TrapperHell** [comment]
Thanks for your comment. Yes, publishing from my own repo is one of the options - considering that I also have made some other changes (in other branches), and the original developer does not seem inclined to take action upon it.

There is currently no code targeting .Net 5, but since it's targeting .Net Standard (starting off from 1.1), I don't see that it will be a big deal to include .Net 5 support.

**Comment by mgibas** [comment]
Indeed I’m out of this project (.net entirely) - I can add you as the collaborator or archive it so you can continue on the other repo, whatever you guys think would work best. Let me know what do you think

**Comment by TrapperHell** [comment]
I guess I am mostly concerned about the NuGet users that will be stuck with an outdated version. I suspect that adding me as a collaborator will do very little with keeping the NuGet up-to-date with future versions.

Unless I am mistaken in my previous statement, I would think that the best way to go forward would be to - if it is possible for you, review / approve / merge this PR and do one final update to your NuGet version so that at least users of the NuGet package can get the QoL updates. Regardless of whether or not this is possible, maybe archive it and optionally set a note to my updated repo?

Those are my thoughts on it. Does this work with you?

**Comment by mgibas** [comment]
Ok let’s start from bumping major version number (appveyor.yml is most important I believe) and merge this PR so it will be available on nuget and we can think about next steps.

**Comment by mgibas** [comment]
On the other note - if collaborators can modify GitHub workflows (not sue why wouldn’t) I could just add a nuget secret and you would have full control over the whole process

**Comment by TrapperHell** [comment]
Version has been bumped to 2.0 for both the appveyor file and the csproj (for good measure).

**Comment by ps30** [comment]
@mgibas or @TrapperHell can one of you merge this PR and squeeze out the updated NuGet now that this is 2.0

**Comment by mgibas** [comment]
Let’s see what’s gonna happen 😀

**Comment by mgibas** [comment]
assembly patching failed on appveyor:
```
Build started
2git clone -q --branch=master https://github.com/mgibas/serilog-sinks-slack.git C:\projects\serilog-sinks-slack
3git checkout -qf eee55d9dfb5c34905df44f32aa8f369c41ff7717
4Patching AssemblyInfo
5No AssemblyInfo files found matching '**\AssemblyInfo.*'
6nuget restore src/Serilog.Sinks.Slack.sln
7Input file does not exist: src/Serilog.Sinks.Slack.sln.
8Command exited with code 1
```
what do you guys want me to do ?

**Comment by TrapperHell** [comment]
😨 sorry about that!

Well, AssemblyInfo doesn't exist anymore with .net core so that's one thing... As for the solution file error, there is no `src` directory to begin with.

**Comment by mgibas** [comment]
That’s fine :) I figured assembly patching and that missing src, now I just need a proper build command (previous msbuild does not make a cut :) ).

**Comment by TrapperHell** [comment]
I might be missing something, but `appveyor.yml` is already set to use `dotnet` instead of msbuild. The file contains the `dotnet` restore / pack commands, but a build can be done using the `dotnet build` command should that be necessary.

**Comment by mgibas** [comment]
Yeah, not sure why appveyor wasn't using that file. Either way I removed it from appveyor and added GH action - nugget key  is in the repo secret so you guys have a full control over this package and its build/publish process. IM OUT! Have fun :)

**Comment by TrapperHell** [comment]
Good stuff with that! One last thing before you see yourself officially out lol, I don't suppose you've actually added me as a collaborator the project? Or if you have, I'm not sure I have the right rights. It doesn't seem like I can push to this repository and neither issue builds. Unless you still want to oversee that aspect?

**Comment by TrapperHell** [comment]
Good stuff with that! One last thing before you see yourself officially out lol, I don't suppose you've actually added me as a collaborator to the project? Or if you have, I'm not sure I have the right rights. It doesn't seem like I can push to this repository and neither issue builds. Unless you still want to oversee that aspect?

**Comment by mgibas** [comment]
You are right, my bad! 🤦🏼‍♂️ Done :)

**Pull request merged**
