### PR TITLE
Downgraded to .NET 4.5

### PR DESCRIPTION
**Pull request by APErebus**
.NET 4.5 is the minimum supported version for Serilog

### CODE REVIEW

**Comment by mgibas** [comment]
What's the puerpouse of this downgrade ?

**Comment by APErebus** [comment]
Serilog supports .NET 4.5, but this sink doesn't.

I figured it made sense to have the same minimum supported version

**Comment by phnx47** [comment]
It https://github.com/mgibas/serilog-sinks-slack/pull/5 will solve your problem

**Comment by mgibas** [comment]
Will take a look into it this weekend (#5 as well)

**Comment by phnx47** [comment]
I couldn't wait and had already published my fork:

https://github.com/Auditorius/Au.Serilog.Sinks.Slack
https://www.nuget.org/packages/Au.Serilog.Sinks.Slack/

And I plan to optimize code

**Comment by mgibas** [comment]
Thanks to @phnx47 and PR #5 we managed to deploy nugget targeting 4.5, 4.6 and Core1.3 👏 
Closing this PR - let me know if you are missing something.

**Pull request closed without merging**
