### PR TITLE
 - Serilog.Sinks.Slack.proj: Updated Serilog to latest, included need…

### PR DESCRIPTION
**Pull request by MirzaMerdovic**
The current version is not working with latest Serilog, I think because PeriodicBatchingSink is now in different library: Serilog.Sinks.PeriodicBatching, so I updated the references.

Also I removed RestSharp dependency and used HttpClient which required Newtonsoft.Json, which made the number of dependencies the same regarding external stuff, but Newtonsoft.Json is much more common one, and in my case RestSharp was something that was used only here.

I did some small refactoring also.

I hope this makes sense to you, if not thank you for the sink anyway :)

### CODE REVIEW

**Comment by mgibas** [comment]
Sorry for late response. Change looks good -  will take some time this or next week. Thanks

**Comment by MirzaMerdovic** [comment]
No problem. Thank you.

**Comment by mgibas** [comment]
Cosmetic fixes and removed a test. Though I would like to put some time into it, this one wasn't testing much - thanks though.

**Comment by mgibas** [comment]
all changes in Serilog.Sinks.Slack.1.0.20

**Comment by MirzaMerdovic** [comment]
Thank you.

**Pull request merged**
