### PR TITLE
Makes Attachments Optional, Other Config Options

### PR DESCRIPTION
**Pull request by alanedwardes**
This ended up being more of a refactor than I planned, but I made the following changes:

- Exposed `ShowDefaultAttachments`, `ShowExceptionAttachments` and `AttachmentColors` in a new `SlackSinkOptions` object
- Renamed `SeqLoggerConfigurationExtensions` to `SlackLoggerConfigurationExtensions`
- Removed `dynamic` from JSON serialisation
- Overrides `Dispose()` on the batch sink, so `HttpClient` can be disposed

The attachments toggling was the main thing I wanted to add, the messages were too big on Slack - I could fit 5 log messages on my screen at once.

### CODE REVIEW

**Comment by mgibas** [comment]
Will take a look at this tomorrow, though quick question: is it compatible with previous version ?
Thanks 👍

**Comment by alanedwardes** [comment]
Thanks. It is yeah, existing overload is still there, it calls the new extension method which accepts the options object.

**Comment by mgibas** [comment]
All looks good for me - please just update [README.md](https://github.com/mgibas/serilog-sinks-slack/blob/master/README.md) with some example.

**Comment by phnx47** [comment]
I merged it and added example.

**Pull request merged**
